thoras-ai/helm-charts

charts/thoras/Chart.yaml

Cutting a new helm release
Bump chart version

Release new version of Helm chart

---

charts/thoras/README.md

Release 3.0.1

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/templates/collector/storageclass.yaml
charts/thoras/templates/monitor/configmap.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/values.yaml

Release 3.1.2

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/monitor/configmap.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/values.yaml

Releasing changes from #43 
This change introduces a new set of configurable parameters to define logging levels for various components of the Thoras ecosystem:
| Key | Type | Default | Description |
| --- | --- | --- | --- |
| logLevel | String | info | Default log level |
| Key | Type | Default | Description |
| --- | --- | --- | --- |
| thorasOperator.logLevel | String | Nil | Logging level |
| Key | Type | Default | Description |
| --- | --- | --- | --- |
| metricsCollector.collector.logLevel | String | Nil | Logging level |
| metricsCollector.purge.logLevel | String | Nil | Logging level |
| Key | Type | Default | Description |
| --- | --- | --- | --- |
| thorasApiServer.logLevel | String | Nil | Logging level |
| Key | Type | Default | Description |
| --- | --- | --- | --- |
| …

Release Chart Version 3.1.6

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Release Thoras version 2.0.10!

Release Thoras version 2.0.10!

---

charts/thoras/values.yaml

In preparation for 4.0.0 release!

Default to new Thoras platform version

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Release helm chart 4.0.2!

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Bump versions to prepare for 4.1.0 release

Prepare 4.1.0 release

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Bump to 4.2.1 helm chart and 3.0.2 thoras

---

charts/thoras/README.md
charts/thoras/values.yaml

Prepare 4.2.2

---

charts/thoras/Chart.yaml

Forgot to do this in https://github.com/thoras-ai/helm-charts/pull/78

Bump chart itself

---

charts/thoras/Chart.yaml
charts/thoras/README.md

Release 4.3.0

---

.github/workflows/release.yml
charts/thoras/Chart.yaml
charts/thoras/README.md

The git command that checks for changes to the version failed
Fix the git command

Fix version check command

---

.github/workflows/release.yml
charts/thoras/Chart.yaml
charts/thoras/README.md

So we can successfully release

Fix grep command for finding version changes

---

.github/workflows/release.yml
charts/thoras/Chart.yaml
charts/thoras/README.md

We were using the wrong GitHub action object -- let's try w/GITHUB_OUTPUT

Fix CI workflow

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Release 4.4.0

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Default to use the newest version of Thoras and release 4.4.1!

Release 4.4.1

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/secret.yaml
charts/thoras/templates/collector/service.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/tests/collector_deployment_test.yaml
charts/thoras/values.yaml

Thoras will be migrating off of Elasticsearch.
Added TimescaleDB. 
TimescaleDB is disabled by default.

Added timescaledb

---

charts/thoras/Chart.yaml
charts/thoras/README.md

Release 4.11.0

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Release 4.13.0

---

charts/thoras/templates/operator/deployment.yaml

Migrating operator to new services image.
operator image  and command updated to use new services image.

Operator image change

---

charts/thoras/Chart.yaml
charts/thoras/README.md

Preparing for release 
version bump!

version bump

---

charts/thoras/Chart.yaml
charts/thoras/README.md

Releasing 4.13.2

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Type in values file 
Bumped app version

Fix app version

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Release 4.15.1

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

We need to automate setting the `postgres` user's password 
We detect this is the first time we're initializing timescaledb, set the password

Automate timescale password setting

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

minor bug fixes
Thoras version 4.3.5

release app 4.3.5

---

charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/tests/collector_cronjob_test.yaml

The collector's environment variables are changing because of our underlying CLI setup.
Updates to the environment variables and parameters to the collector `prune` and `collect` commands.

Update collector environment variables

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Release 4.16.3

---

charts/thoras/Chart.yaml

I knew I forgot something for the release

Bump chart version to 4.17.0

---

charts/thoras/README.md

Docs should reflect new values we introduce
Add documentation of new qps value

Update docs for qps value

---

charts/thoras/Chart.yaml
charts/thoras/README.md

Release 4.19.0

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

prepare for release 4.24.0

---

charts/thoras/Chart.yaml
charts/thoras/README.md

Release 4.25.0

---

charts/thoras/Chart.yaml
charts/thoras/README.md

This release includes the new scaling behavior settings in the AST CRD

Release 4.30.0

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

* Make forecast-via-queue the default Thoras behavior 
* Release 4.31.0

Release 4.31.0

---

charts/thoras/templates/api-server-v2/service.yaml
charts/thoras/templates/collector/service.yaml
charts/thoras/templates/dashboard/service.yaml
charts/thoras/templates/operator/service.yaml
charts/thoras/templates/reasoning-api/service.yaml
charts/thoras/tests/__snapshot__/dashboard_service_test.yaml.snap

[4.32.3] Add name to service ports

---

charts/thoras/templates/dashboard/nginx-config-map.yaml
charts/thoras/tests/__snapshot__/dashboard_configmap_test.yaml.snap

Thoras will enjoy the ability to share paths to dashboard pages without encountering 404 errors.
An updated nginx configuration has been implemented to proxy all paths to index.html, enabling the React SPA to handle the routing requests.

proxy all paths to index.html

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/tests/dashboard_configmap_test.yaml
charts/thoras/tests/dashboard_service_test.yaml
charts/thoras/values.yaml

Releasing changes
minor app changes

Release 4.36.1

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Release 4.40.1

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Release 4.42.1

---

charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/forecast-worker/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/operator/deployment.yaml

Various services are dependent on the API service for starting and should be dependent on that service.
Introducing init containers for containers dependent on the API service.

Introduce dependencies on API service

---

.github/pull_request_template.md

It would be clutch to understand which PRs correlate to which customer enhancements.
You have 1 more line to fill out during PRs- selfish I know.
Customers could also track changes!

Update pull_request_template.md with customer impact question

---

charts/thoras/templates/crd/aiscaletarget.yaml

Better scaling coverage. 
Updating forecast default in AST CRD.

Update forecast defaults

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/values.yaml

Fixing the spelling on the `SERVICE_TIMESCALE_SNAPSHOTS_PRIMARY` flag.
Fixing the spelling on the `SERVICE_TIMESCALE_SNAPSHOTS_PRIMARY` flag.

Updating `SERVICE_TIMESCALE_SNAPSHOTS_PRIMARY` flag

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

- Bump chart version to 4.50.0
- Update thorasVersion to 4.37.0
- Update README.md version badges

Release 4.50.0

---

charts/thoras/templates/worker/rbac.yaml

Gives the Thoras worker the ability to watch objects.
Added watch to throas worker rbac
[ x ] Do any feature flags need to be managed?

Added watch

---

charts/thoras/Chart.yaml
charts/thoras/README.md

Minor changes to thoras-worker RBAC.
Update thoras-worker allowed verbs. 
[x] Do any feature flags need to be managed?

Release Chart 4.55.5
