thoras-ai/helm-charts

.github/workflows/release.yml

We've open sourced the Thoras AI Helm chart! Now we need a way to automatically publish new helm releases
Add GitHub action that publishes new Helm chart releases on commits to `main`

Add helm chart release GH action

---

charts/thoras/Chart.yaml
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/purge-forecast-hook.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/operator/deployment.yaml

* Currently there's no way for users to specify what specific forecast version should be run. We need to give them that control
* `image` is less accurate of a value name than `imageTag` so we'll want to level up our naming accuracy
* Provide new environment variable called `MODEL_IMAGE` that enables the user to specify the desired forecast image tag
* Rename instances of `image` to the more accurately named `imageTag`

Use imageTag to override deployment images 

---

charts/thoras/Chart.yaml
charts/thoras/templates/operator/deployment.yaml

It'd be useful for the application to know the helm  version so we can make decisions based off of that, if needed (such as for backwards compatibility)
Assign the helm chart version as the value to a new env var in the operator component called `THORAS_VERSION`

Added chart version env var to operator

---

.github/pull_request_template.md
charts/thoras/Chart.yaml
charts/thoras/templates/collector/deployment.yaml

We unintentionally changed the convention for how we reference our backend metrics collection pod. Its convention is to use `.image` which is a full <image>/<tag> combo, unlike Thoras components which usage `.imageTag` to specify only the tag.
* Use the correct value for specifying backend metrics container image
* Also add a PR template while we're here
* Bump to 2.1.3

Fix metrics backend image name

---

charts/thoras/Chart.yaml
charts/thoras/values.yaml

Generally speaking the latest helm chart version should default to using the latest app version. This change is ensuring that's true
Set the default Thoras version to be the latest stable version of Thoras

Bump default app version to latest stable

---

charts/thoras/Chart.yaml
charts/thoras/values.yaml

We've published a new version of the Thoras platform (`1.1.1`). We want to make sure we publish a new helm chart that defaults to using it
Default to the newest stable version of Thoras: `1.1.1`

Default thoras version to latest stable (1.1.1)

---

charts/thoras/templates/crd/aiscaletarget.yaml

We want to be able to iterate on how CRD properties are used , which might involve changing a type. But we want to do that in a backwards compatible way, which this change ensures for `forecast_blocks`
Allow `forecast_blocks` to be a string or an int

Allow int or str for forecast_blocks

---

charts/thoras/Chart.yaml
charts/thoras/values.yaml

We want the latest helm chart to default using the latest Thoras release (`1.1.2`)
Set `thorasVersion` to `1.1.2`

Default thoras version to latest stable release

---

charts/thoras/Chart.yaml
charts/thoras/values.yaml

Using the latest version of the Thoras chart should default to installing the latest version of Thoras (`1.1.3`)
Default to Thoras version `1.1.3`

Default to thoras 1.1.3

---

charts/thoras/Chart.yaml
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/values.yaml

The pursuit of high availability is always happening. We're always looking for ways to optimize resilience and lower the chances of issues
* Give the api server 3 replicas instead of 1
* On deployment updates, ensure the metrics collector gets terminated before spinning up a new pod

HA improvements

---

charts/thoras/values.yaml

We should have the latest chart default to the latest stable release
Set the default version Thoras to `1.1.5`

Bump chart and default Thoras version, 1.1.5

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/values.yaml

It's important to give users the ability to change their collector init image tag
* Parameterize collector init image tag
* Use Thoras image registry

Parameterize collector init image

---

charts/thoras/Chart.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/values.yaml

Release Chart 2.6.0!

---

charts/thoras/Chart.yaml
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/purge-forecast-hook.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/values.yaml

1. We've migrated to a new container image registry so we need to update the default. We consider this a breaking change, so we're bumping to `3.0.0`
2. Historically we've set `imagePullPolicy` to `Always` since we've had several use-cases for using the `:latest` image tag. We don't have that use-case anymore so let's allow users to cache their images on nodes which is the default Kubernetes behavior
* Set new defaults for image registry and have them use the new registry name and username
* Make `imagePullPolicy` configurable and default to `IfNotPresent`

New registry and image pull policy

---

charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/purge-forecast-hook.yaml

Metrics purge job pod fails on startup. 
Fixed entry point arguments so that metrics purge job can start.

Fix metrics purge entry point arguments 

---

charts/thoras/README.md
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/monitor/secret.yaml
charts/thoras/values.yaml

We are adding a new service that monitors and alerts users of various potential issues both in their infrastructure and on the thoras platform (e.g. a deployment going down).
Added new deployment and corresponding values for `thoras-monitor`.

add thoras-monitor deployment

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

Releasing chart version `3.1.0`

Bump to chart 3.1.0

---

charts/thoras/README.md
charts/thoras/templates/collector/storageclass.yaml
charts/thoras/values.yaml

Users shouldn't have to set up an EFS `StorageClass` object in their cluster if they want to use EFS for Thoras in addition to the easiest install experience possible
* Create the ability for users to automatically create a dedicated thoras `StorageClass` that's bound to the Thoras EFS volume
* Update docs
* Set a default `storageClassName` since users who want this automated probably don't want to have to think about its name

Provide ability to autocreate StorageClass for Thoras EFS volume

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

We've released a new version of the Thoras Platform (`2.0.10`) and we want to ensure the latest helm chart defaults to using it
Default Thoras Platform version to 2.0.10

Default to Thoras version 2.0.10

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/values.yaml

To turn on sending `error`-level logs to slack, we need to expose the environment variables.
Needed for https://github.com/thoras-ai/platform/pull/73
This PR adds global and service-level configurations for `SLACK_WEBHOOK_URL` and `SLACK_ERRORS_ENABLED`. In the case of `thorasMonitor`, the webhook URL makes the passing of workspace, channel and hook IDs obsolete.

Add SLACK_WEBHOOK_URL and SLACK_ERRORS_ENABLED to helm charts

---

charts/thoras/README.md
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/monitor/secret.yaml
charts/thoras/templates/operator/deployment.yaml

When converting over to the webhook URL in #49, I didn't make it a secret
I think this captures the effort in turning the `slackWebhookUrl` into a secret.

Convert the slackWebhookUrl into a secret

---

charts/thoras/templates/monitor/secret.yaml

Since we have one URL at the top level, we need to reference that var!
Update monitor template to reference top level Slack webhook URL var

One SlackURL var to rule them all!

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/api-server-v2/service.yaml
charts/thoras/values.yaml

We have a new API service layer that needs to be added to the chart for it to be released.
Adding a new, `thoras-api-server-v2` deployment and service. The service is default off unless the value `thorasServerV2.enabled == true`.

Add  v2 API service

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/values.yaml

We don't need to set CPU limits and increasing the memory limit will reduce future OOMs
- Removing `limits.cpu` in all cases
- Bumping `limits.memory` to 2000Mi in all cases

Drop CPU limits; bump memory to 2Gi

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/values.yaml

We want to provide a helm chart that defaults to the latest version of Thoras
Bump default app version to 2.1.1

Default to newest app version, 2.1.1

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/api-server-v2/service.yaml
charts/thoras/values.yaml

The API service layer is ready for deploying every where, not just where enabled.
The API service layer is an internal service used by various components to store and retrieve data from Kubernetes and our internal storage. Initially, none of these components are using the service layer, but we'll soon be moving various components to the new service until all components are going through the layer.

Enable API service layer

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/templates/monitor/secret.yaml

[We expect](https://github.com/thoras-ai/helm-charts/blob/dev/charts/thoras/templates/operator/deployment.yaml#L50) the `thoras-slack` secret to be present, so create it no matter what -- even if the content is empty
Removed conditions for if we create a Slack secret (always create it)

Always create slack secret

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/values.yaml

To add TLS support to the API service layer, we need to pass the certificate and key file.
Updating the API service layer command to include the TLS certificate and key files and updating the ports to be on 443.

Add TLS support to API service layer

---

charts/thoras/templates/crd/aiscaletarget.yaml

This enhancement introduces the ability to target specific containers within deployments for vertical scaling, enabling fine-grained control over resource allocation and optimization. 
The `AIScaleTarget` Custom Resource Definition (CRD) has been updated to include a `containers` list within the `vertical` spec. This list allows users to specify individual containers for vertical scaling by their name. Memory upper and lower bounds remain optional. 
**Example `AIScaleTarget` CRD:**
```yaml
apiVersion: thoras.ai/v1
kind: AIScaleTarget
metadata:
name: test-vertical
namespace: test-mutate
spec:
scaleTargetRef:
kind: Deployment
name: test-vertical
model:
mode: balanced
vertical:
mode: autonomous
containers:
- name: nginx
memory: 
lowerbound: 250Mi
upperbound: 4Gi
```
**Backwards …

Added containers list to vertical spec

---

charts/thoras/templates/dashboard/deployment.yaml

The dashboard service needs to start talking to the V2 api server by environment variable
Adding an `API_BASE_URL` environment variable to the dashboard service that references the the API v2 service.

Add API_BASE_URL to dashboard

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/templates/collector/pvc.yaml

If users provision a PV out-of-band from the Thoras installation, they should be able to reference that PV and be done with it.
The issue is that in that case, we'll still set the `storageClassName` field which is no longer applicable and could cause undesired behavior
Make the helm chart not set `storageClassName` field on the PVC when `volumeName` is set by the user

Fix direct volume name assignment

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/values.yaml

I recently switched the dashboard to use the new api service layer, but there are TLS errors that break the fetching of data for the graphs on the dashboard. This PR switches off the TLS settings until I can figure out what the issue is. I'm not sure if it's an issue with the dashboard talking to the API service layer or something else.
Example error: 
```
thoras-api-server-v2-75bb7795c4-skzw8 thoras-v2-api-server 2024/10/18 15:22:19 http: TLS handshake error from 10.128.33.155:56608: EOF
```
Turning off TLS for the API service layer. I filed https://github.com/thoras-ai/helm-charts/issues/69 to turn TLS back on

Turn off TLS for api-v2 server

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/values.yaml

Users may want to configure CPU requests for forecasts for various reasons
One consideration here is if a user sets a non-trivial cpu request it's always possible the forecast has to wait for autoscaler to spin up a new node which could add ~45-120 seconds to the time the forecast is allowed to start 
Add conditional env var on the operator deployment that causes cpu request to be set on the forecast cron, if defined
We decided not to include limits or memory requests in this change to keep it simple and focused on current use-case

Allow specifying forecast cpu requests

---

charts/thoras/values.yaml

We want the latest helm chart to use the latest stable Thoras version
Defaulting Thoras version to latest stable, 3.0.1

Bump default thorasVersion to 3.0.1

---

charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/operator/deployment.yaml

To ensure consistency and maintainability across the platform, it is recommended to standardize the image pull policy for all components, including forecast cron jobs. Currently, the pull policy for these jobs differs from the rest of the platform, potentially leading to inconsistencies and operational difficulties.
We are introducing a new environment variable, `FORECAST_IMAGE_PULL_POLICY`, within both the operator and dashboard containers. This variable is set to the helm value `imagePullPolicy`. No change is required for any current values files. This variable will be utilized when configuring the `imagePullPolicy` setting for the forecast cron job.
This change will ensure that the image pull policy for forecast cron jobs aligns with the platform's best practices, promoting …

Added FORECAST_IMAGE_PULL_POLICY env var to operator and dashboard

---

charts/thoras/templates/crd/aiscaletarget.yaml

Users should have a way to define a "safety buffer" that gets added to their usage forecasts so that they can have increased confidence that there won't be disruption.
Add `spec.mode.forecast_buffer_percentage` field to the `AIScaleTarget` CRD. Can be an integer or string

Add forecast_buffer_percentage field

---

.github/workflows/ci.yml
.github/workflows/release.yml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/templates/reasoning-api/service.yaml
charts/thoras/tests/component_not_enabled_test.yaml
charts/thoras/tests/deployments_test.yaml
charts/thoras/values.yaml

We need to be able to deploy the Thoras Reasoning API
**It's currently disabled by default**
* Add Thoras Reasoning API
* Fix CI config so that we only try to publish a new release when there's a new chart version
* Add unit tests

Add Reasoning API component

---

charts/thoras/templates/api-server-v2/deployment.yaml

In order to talk to the internal reasoning API, we need to plumb an environment variable through to the service.
Adding a `SERVICE_REASONING_API_URL` that points to the reasoning service. It's prefixed with `SERVICE_` because that's how the [huma cli](https://huma.rocks/features/cli/#passing-options) expects environment variables to be prefixed. 
Also fixing a couple other environment variables that were previously being handled by [envconfig](https://github.com/kelseyhightower/envconfig) but weren't changed when we switched them to huma.

Add environment variable for reasoning API endpoint

---

charts/thoras/templates/agent/daemonset.yaml

In order to collect eBPF metrics, the agent container must be running with `securityContext: privileged: true`, not the pod.
I'm moving the `securityContext` block to the container from the pod. Without doing this, we get permission errors when starting the agent, like this:
```
time=2024-11-05T17:31:22.310Z level=ERROR msg="Failed to initialize collector" err="loading eBPF objects: field TcpCleanupRbuf: program tcp_cleanup_rbuf: load program: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)"
panic: loading eBPF objects: field TcpCleanupRbuf: program tcp_cleanup_rbuf: load program: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)
```

Move securityContext from pod to container

---

charts/thoras/templates/crd/aiscaletarget.yaml

This enhancement introduces a new feature that allows Thoras users to specify metrics for the Thoras Forecaster to use for predictions and recommendations, independent of the metrics used by the target HPA for scaling.
A new `spec.scale_metrics` property has been added to the AIScaleTarget CRD. Example configuration:
```
---
apiVersion: thoras.ai/v1
kind: AIScaleTarget
metadata:
name: nginx-target
namespace: keda
spec:
horizontal:
mode: recommendation
model:
forecast_buffer_percentage: 10%
forecast_cron: '*/10 * * * *'
mode: balanced
scale_metrics:
- external:
metric:
name: s0-aws-cloudwatch
selector:
matchLabels:
scaledobject.keda.sh/name: rtb-bidder
target:
averageValue: "1"
type: AverageValue
type: External
scaleTargetRef:
kind: Deployment
name: avg-deployment
```

External metrics crd

---

charts/thoras/templates/crd/aiscaletarget.yaml

Preparing the AIScaleTarget CRD for a new reasoning feature. 
Added new `spec.reasoning.metrics` list that allows the user to configure where their custom metrics live and how to query them. 
Example:
```yaml
apiVersion: thoras.ai/v1
kind: AIScaleTarget
metadata:
name: game-server
namespace: battle-all-nite
spec:
horizontal:
mode: autonomous
model:
forecast_blocks: 60m
forecast_cron: '*/15 * * * *'
mode: balanced
reasoning:
metrics:
- name: http_requests_total
query: http_requests_total{environment=~"staging|testing|development",method!="GET"}
connector: prometheus
scaleTargetRef:
kind: Deployment
name: game-server
vertical:
mode: recommendation
```

Added reasoning metrics list

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/rbac.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/dashboard/rbac.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/monitor/secret.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/templates/operator/rbac.yaml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/templates/registry-secret.yaml
charts/thoras/tests/secrets_collector_test.yaml
charts/thoras/tests/secrets_test.yaml
charts/thoras/values.yaml

A common pattern that some customers expect is the ability to reference existing secrets instead of passing in sensitive values to the helm chart for secret population.
* Make it possible to reference an existing registry secret
* Make it possible to reference an existing Slack URL secret
* Add unit tests
* I re-ordered some env vars to make the Slack env variables in a consistent order. Shouldn't hurt anything
* Implementing Prometheus endpoint env var for reasoning-api directly after this

Enable secret-by-reference

---

charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/tests/reasoning_api_deployment_test.yaml
charts/thoras/values.yaml

* Customers need the ability to configure their prometheus base URL for us to ingest prome metrics
* Give customers the ability to configure prometheus base endpoint via  `thorasReasoningApi.connectors.prometheus.baseUrl` value
* This is a smallest useful thing -- we talked about probably needing something more sophisticated for managing connector config in the long term

Add configurable prometheus base URL for reasoning api

---

charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/purge-forecast-hook.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/tests/collector_deployment_test.yaml
charts/thoras/values.yaml

Migrating to a newer better metrics collector 
Removing old metrics collector image in favor of a newer one.

Migrate to go collector

---

charts/thoras/README.md
charts/thoras/templates/collector/pvc.yaml
charts/thoras/tests/pvc_test.yaml
charts/thoras/values.yaml

Users need to be able to specify `spec.resources.requests.storage` on their PVC -- especially in case they're using a fixed storage size backend (such as AWS EBS)
* Make `spec.resources.requests.storage` configurable
* Default to "3Gi"
* Add unit tests
* Update documentation

Make PVC requests.storage configurable

---

charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

We need to plumb the `API_BASE_URL` to the API service layer to all the deployments that will use the service layer.
Adding an environment variable `API_BASE_URL` to deployments in addition to the `dashboard` deployment.

Add API_BASE_URL environment var to other deployments

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/api-server/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/tests/dashboard_deployment_test.yaml
charts/thoras/tests/deployments_test.yaml
charts/thoras/values.yaml

The best practice for open source helm charts is to default deployments to 1 replica because:
- Letting the user decide what they need is more aligned with a user-driven config approach, which is more ideal
- It's less expensive
- Avoids premature scaling
- Is easier to understand and navigate for new users
Default replicas to 1 for all `Deployments`

Default to single replica for services

---

charts/thoras/tests/reasoning_api_deployment_test.yaml
charts/thoras/tests/secrets_collector_test.yaml
charts/thoras/tests/secrets_test.yaml

When adding a new environment variable for some services, I was burned by tests that were too rigid in the expected order of environment variables.
Updating some tests to care less about the index of environment variables and more about what the environment variables look like, using [jsonpath](https://github.com/json-path/JsonPath)

Make helm unit tests more flexible with environment variable checks

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/api-server-v2/rbac.yaml
charts/thoras/tests/__snapshot__/api_service_deployment_test.yaml.snap
charts/thoras/tests/api_service_deployment_test.yaml
charts/thoras/values.yaml

The v2 api server will need to be able to access kubernetes resources.
A service account with a corresponding cluster role has been created and assigned to the v2 API server to grant the necessary resource access.

Added rbac for v2 api

---

charts/thoras/templates/operator/deployment.yaml

Users can configure which namespace to run Thoras in. That config needs to propagate to the operator to ensure CronJobs get created in the correct namespace
Pass user-defined Thoras namespace into the operator env var

Configure operator to use correct namespace

---

charts/thoras/templates/reasoning-api/deployment.yaml

Since python's single-threaded, Flask by itself is not sufficient for non-development use-cases. We need a WSGI server to act as a reverse proxy so concurrent HTTP calls are managed properly. Luckily this is a well-established pattern and easy to do
Run reasoning API via gunicorn

Run reasoning api via gunicorn in prod

---

charts/thoras/templates/crd/aiscaletarget.yaml

This change addresses user requests for the ability to exclude metrics from AIScale while retaining the functionality of Horizontal Pod Autoscaling (HPA) based on those same metrics.  This allows for more granular control over resource management and scaling.
The `exclude_metrics` field has been added to the `spec.horizontal` section of the configuration, allowing users to specify metrics to exclude from AIScale.  The supported metric types are: `External`, `Resource`, and `Object`.  An example configuration is shown below:
```yaml
exclude_metrics:
- type: External
name: aws-alb-latency
- type: Resource
name: cpu
- type: Object
name: requests-per-second
```
Furthermore, the `spec.scale_metrics` field has been relocated to `spec.horizontal` for improved configuration organization and …

Update ast metric

---

charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/templates/reasoning-api/service.yaml
charts/thoras/tests/component_not_enabled_test.yaml
charts/thoras/tests/deployments_test.yaml
charts/thoras/tests/reasoning_api_deployment_test.yaml
charts/thoras/tests/secrets_test.yaml
charts/thoras/values.yaml

Some reasoning-related info is relevant to workloads that aren't the reasoning API, specifically. Let's refactor the reasoning variable in a way that makes this clear
* get rid of `.Values.thorasReasoningApi`
* put all previous data underneath `.Values.thorasReasoning.api` _with the exception of `connectors`_ which would be under `thorasReasoning`

Refactor reasoning variable to make scope clearer

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/templates/reasoning-api/service.yaml
charts/thoras/tests/component_not_enabled_test.yaml
charts/thoras/tests/deployments_test.yaml
charts/thoras/tests/reasoning_api_deployment_test.yaml
charts/thoras/tests/secrets_test.yaml
charts/thoras/values.yaml

For the service layer to query prometheus, it needs the URL to prometheus
Adding the `SERVICE_PROMETHEUS_API_URL` environment variable which points to the prometheus base url

Add prometheus api URL to service layer environment

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/secret.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

We need an init container that will migrate timescale database versions.
I'm adding an init container that will wait for timescaledb and then migrate the database versions. I put the init container on the v2 service because (a) the migrations will likely be associated with a API service layer change and (b) because the init container can't be in the same deployment as the timescaledb container because it requires timescaledb to be up and running before it can run.

Use dbmate to migrate database

---

charts/thoras/templates/api-server-v2/deployment.yaml

The service layer needs the postgres/timescale DB DSN passed to it a certain way so it can connect to postgres to store metrics.
Changing the environment variable to align with how [huma](https://huma.rocks/features/cli/#passing-options) expects it to be passed.

Send postgres url to api-v2

---

charts/thoras/templates/crd/aiscaletarget.yaml

It's important that if the user doesn't specify a forecast buffer percentage that the system continues to chug along. So let's provide a sane default
Set `forecast_buffer_percentage` default to `"0"`

Set default field for forecast_buffer_percentage

---

charts/thoras/templates/crd/aiscaletarget.yaml

We should provide a sane default window for `forecast_blocks` that aligns with the default cronjob window of once per 15m
Default `forecast_blocks` to `"15m"`

Default forecast_blocks to "15m"

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

Elasticsearch should be initialized with indices before starting the metrics collector 
Added init script to start of metrics collector

added init to start of metrics collector

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/tests/collector_deployment_test.yaml
charts/thoras/tests/secrets_collector_test.yaml
charts/thoras/values.yaml

TimescaleDB is always configured to run even when no timescale-related values are present in the config. 
1. Remove timescale container validation
2. Update the unit testings accordingly
3. Update default timescale input passing in the values.yml

Make default enabled timescale DB

---

charts/thoras/templates/agent/daemonset.yaml
charts/thoras/templates/agent/rbac.yaml
charts/thoras/values.yaml

The thoras agent should use a different service account than the metrics collector.
When I created the agent, instead of creating a proper RBAC role and service account for it, I reused the same service account from the metrics collector. This was tech debt that this PR now fixes.

Add separate service account for agent

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/tests/secrets_test.yaml
charts/thoras/values.yaml

Update our helm chart to allow customers to pass in the name of the cluster in a way that propagates the cluster name to an environment variable in the services application
- Customers can define the name of their cluster in the helm chart installation config (values.yaml)
- Adding unit test that asserts this behavior works in the helm chart

Pass SERVICE_CLUSTER _NAME environment variable from value.yaml

---

charts/thoras/templates/agent/daemonset.yaml
charts/thoras/templates/agent/rbac.yaml
charts/thoras/values.yaml

In order to map IP addresses to deployments, we need to be able to query the k8s API to list the deployments and pods for each deployment.
Updating the agent rbac rules to allow for `get/list` against any API

Give agent service account permission to query K8s for deployments and pods

---

charts/thoras/templates/monitor-v2/deployment.yaml
charts/thoras/templates/monitor-v2/rbac.yaml
charts/thoras/templates/operator/rbac.yaml
charts/thoras/tests/monitor_v2_deployment_test.yaml
charts/thoras/values.yaml

create the the ability to deploy new app monitor-v2 via helm chart.
(https://github.com/thoras-ai/platform/issues/494)
There's a new top-level config block in our helm chart called thorasMonitorV2.enabled
When this variable is set to true, a new Kubernetes Deployment is created in the Thoras installation
There are unit tests that assert no deployment is created when the variable is false and vice versa

494 Create end-to-end scaffolding go app for monitor-v2

---

charts/thoras/templates/collector/rbac.yaml
charts/thoras/templates/operator/rbac.yaml

The `thoras-operator -> thoras-operator` ClusterRoleBinding was removed in #142 erroneously and needs to be restored.
This PR restores the ClusterRoleBinding removed in #142 and moves the `thoras-collector` ClusterRoleBinding to the collector's RBAC files.

Restore missing ClusterRoleBinding for the thoras-collector

---

charts/thoras/tests/monitor_v2_deployment_test.yaml

When running the tests locally (not in CI, for some reason), the following error is generated:
```
FAIL  Monitor-V2       charts/thoras/tests/monitor_v2_deployment_test.yaml
- Should create deployment when thorasMonitorV2.enabled is false
- asserts[0] `notExists` fail
Template:       thoras/templates/monitor-v2/deployment.yaml
```
This PR fixes that error by checking for documents instead of using `notExists`
Also, this PR fixes the incorrect YAML warning:

Fix broken unit test for monitor-v2 deployment

---

charts/thoras/templates/operator/deployment.yaml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/templates/reasoning-api/service.yaml
charts/thoras/tests/component_not_enabled_test.yaml
charts/thoras/tests/deployments_test.yaml
charts/thoras/tests/operator_deployment_test.yaml
charts/thoras/tests/reasoning_api_deployment_test.yaml
charts/thoras/tests/secrets_test.yaml
charts/thoras/values.yaml

… testings
Customers able to configure reasoning and disable the reasoning feature if needed.
related to https://github.com/orgs/thoras-ai/projects/6/views/3?pane=issue&itemId=93006500&issue=thoras-ai%7Cplatform%7C528
- Implementing enabled toggle within the thorasReasoning configuration to control by the user. 
- Updating the deployment and service configuration files and unit testings to respond with its changes. 
- Updating API_BASE_URL to OPERATOR_THORAS_API_BASE_URL

528 Disabling Reasoning in helm chart should work as expected

---

charts/thoras/templates/operator/deployment.yaml
charts/thoras/tests/operator_deployment_test.yaml

Fixing bug with taking the correct prefix environment variables via huma cli. 
related to https://github.com/thoras-ai/helm-charts/pull/147
Updating OPERATOR to SERVICE prefix

Updating env variable to SERVICE

---

charts/thoras/templates/collector/cronjob.yaml
charts/thoras/tests/collector_cronjob_test.yaml

The user's nightly metrics purge cron job is failing due to missing PostgreSQL environment variables.
PostgreSQL environment variables have been added to the metrics cron job to resolve the issue and ensure successful execution.
fixes thoras-ai/platform#580

Add Postgres config to metrics purge cronjob

---

charts/thoras/templates/api-server-v2/deployment.yaml

The API service layer should wait for timescale/postgres instead of crashing during start.
Adding an init container that waits for timescale/postgres to be available before handing off to the main container.
Should cut down on errors in our slack channels, like this:
```
error
failed to connect to user=postgres database=thoras:
172.20.118.24:5432 (timescale): dial error: dial tcp 172.20.118.24:5432: connect: connection refused
172.20.118.24:5432 (timescale): dial error: dial tcp 172.20.118.24:5432: connect: connection refused
```

Wait for postgres before starting api server

---

charts/thoras/templates/crd/metricconnector.yaml

As a Thoras engineer, I should be able to configure the Reasoning engine's metrics insights feature to ingest a specific subset of a timeseries db (versus ingesting the entire database) so that I can have a smaller batch of data to develop against. Having a way of narrowing the data will make it easier to focus on feature development because the pipelines will be quicker and there will be less metric data, making it more clear
The [MetricsConnector](https://github.com/thoras-ai/helm-charts/blob/main/charts/thoras/templates/crd/metricconnector.yaml) CRD has a field that allows the user to specify a prometheus query to limit how much data is ingested from "the whole thing" to "just a single metric"
related to [574](https://github.com/orgs/thoras-ai/projects/6/views/3?pane=issue&itemId=938779 …

Add private single_metric scope field to connector CRD, for narrowing data ingest for development

---

charts/thoras/README.md
charts/thoras/templates/agent/daemonset.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/monitor-v2/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/tests/secrets_collector_test.yaml

The slack error reporting-related environment variables need to be updated for our services.
We changed several environment variables around sending error messages to slack, including those for the collector, operator, monitor-v2 and the agent.

Update slack error reporting-related env vars

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

In moving around some environment variables, I introduced a duplicate `SERVICE_CLUSTER_NAME` for the collector deployment, which would trigger a helm chart apply error.
- Dropping the duplicate `SERVICE_CLUSTER_NAME` env var for the collector
- Also re-adding the `DATABASE_URL` environment variable removed in #156 because the collector still depends on it for migrations.

Remove duplicate SERVICE_CLUSTER_NAME env var

---

charts/thoras/templates/crd/aiscaletarget.yaml

To prioritize maintainability and alignment with Kubernetes tools as well as improve the user experience of working with ASTs  we need to migrate to a generated AST CRD.
The legacy hand built AST CRD has been replaced with a controller-tools generated CRD that will improve usability as well as input validation.

Use generated AST CRD

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

Huma expects SERVICE_LOGLEVEL not SERVICE_LOG_LEVEL
Switch loglevel env var to Huma-expected SERVICE_LOGLEVEL

Huma expects SERVICE_LOGLEVEL not SERVICE_LOG_LEVEL

---

charts/thoras/templates/api-server-v2/deployment.yaml

The service layer needs to know where to store artifacts and other blobs.
- Associate the service layer with the PVC
- Pass the storage path to the service layer via environment variable

Pass artifact storage path to api service layer

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

Restoring the `POSTGRES_PASSWORD` removed erroneously in #156 so that the collector can set the correct password on startup.

Add POSTGRES_PASSWORD to collector environment

---

.github/workflows/release.yml

In order to tag hotfix releases, we need to run the chart releaser when the version changes on any branch prefixed with `release` 
Updating our github release action to include branches prefixed with `release`

Run chart releaser for release** branches

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

Fixes the following error: 
```49046 warnings.go:70] spec.template.spec.containers[2].env[6]: hides previous definition of "SERVICE_LOG_LEVEL", which may be dropped when using apply```
Introduced in https://github.com/thoras-ai/helm-charts/pull/165
Remove the duplicate `SERVICE_LOG_LEVEL` on the collector

Remove duplicate SERVICE_LOG_LEVEL

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/monitor-v2/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

The environment variable for the service layer API endpoint has changed.

Update service API environment variable

---

.github/workflows/release.yml

We shouldn't immediately build branches prefixed with `release` but should be able to manually trigger the workflow via the github UI.

Don't build release branches

---

charts/thoras/templates/collector/deployment.yaml

On a fresh install, timescale/postgres goes into a crashbackoff loop because it doesn't have perms to make the data dir
Mounting and running `mkdir -p` and `chown` in an init container when starting the metrics collector.

Create and chown timescale directory

---

charts/thoras/Chart.yaml
charts/thoras/README.md

Bump helm chart to 4.16.1

---

charts/thoras/templates/crd/aiscaletarget.yaml

The `exclude_metrics` was dropped from the AST CRD in https://github.com/thoras-ai/helm-charts/pull/164 when it shouldn't have been.

Add exclude_metrics back into AST CRD

---

charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/dashboard/nginx-config-map.yaml
charts/thoras/templates/dashboard/service.yaml
charts/thoras/tests/__snapshot__/dashboard_service_test.yaml.snap
charts/thoras/tests/dashboard_deployment_test.yaml
charts/thoras/tests/dashboard_service_test.yaml
charts/thoras/tests/secrets_test.yaml
charts/thoras/values.yaml

To streamline communication between the frontend and the API server, we are exposing the API server on the same port as the dashboard. This eliminates the need for a Backend-for-Frontend (BFF) layer, allowing the frontend to make direct HTTP requests to the API server.
An Nginx container has been added to the dashboard pod, acting as a reverse proxy for both the dashboard and the API server on the same port. This ensures seamless integration while maintaining a simplified architecture.

Added Nginx reverse proxy to dashboard exposing api server

---

charts/thoras/templates/agent/daemonset.yaml
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/operator/deployment.yaml

We need a way to override the default k8s rate limiting "queries per second" or QPS. Future work to introduce short-window caching of target k8s queries.

Allow queries-per-second overrides

---

charts/thoras/README.md
charts/thoras/templates/operator/deployment.yaml
charts/thoras/tests/operator_deployment_test.yaml
charts/thoras/values.yaml

Thoras forecaster now has the ability to disable the model cache! 
Added value `thorasForecast.skipCache`

Added MODEL_SKIP_CACHE to op

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap

The metrics collector now supports collecting metrics in parallel instead of serially.
This PR adds a new optional field (defaults to 20) that controls the number of AST metrics to be collecting in parallel.

Add env variable to collector for controlling parallelization

---

charts/thoras/templates/agent/daemonset.yaml
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/values.yaml

We want to set a liberal limit to the Kubernetes client QPS so that Thoras supports large installations out-of-the-box. This value doesn't mean the client will call the k8s api this many times -- only if it's needed
Explicitly set qps for all services that use the k8s client, and default it to 50

Set a default max qps for all services

---

charts/thoras/Chart.yaml
charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml

Need to change ownership on the blob storage directory to clear up a `permission denied` error when accessing blobs.

Release 4.17.3

---

charts/thoras/templates/collector/cronjob.yaml
charts/thoras/tests/collector_cronjob_test.yaml

Metric retention cronjob currently fails to respect when users specify a Slack secret reference
This pull request introduces changes to the `charts/thoras` directory, specifically improving the handling of Slack webhook URL configurations and updating the corresponding tests. The most important changes include adding conditional logic for Slack webhook URL secrets in the `cronjob.yaml` file and enhancing the test coverage in the `collector_cronjob_test.yaml` file.
Improvements to Slack webhook URL configuration:
* [`charts/thoras/templates/collector/cronjob.yaml`](diffhunk://#diff-fba3c0b424ee89fa9792d2955fe6edf5b84dff5fe302883e9754c9ec478a26f4R29-R35): Added conditional logic to use custom Slack webhook URL secret references if provided, otherwise default to the existing secret. …

Cleanup CronJob should respect Slack secret reference

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/collector/cronjob.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/purge-forecast-hook.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/monitor-v2/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/tests/collector_cronjob_test.yaml
charts/thoras/tests/deployments_test.yaml
charts/thoras/tests/operator_deployment_test.yaml
charts/thoras/values.yaml

Users need the ability to assign workloads to nodes with specific labels. This can be done multiple ways but one of the [simplest and most common ways is via node labels](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/). Our helm chart should provide the ability to run the Thoras platform on nodes with a specific label
* Provide users the ability to run Thoras on nodes with a particular label
* Unit tests
* Updated docs

Allow assigning workloads to nodes

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/monitor-v2/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/tests/api_service_deployment_test.yaml
charts/thoras/tests/collector_deployment_test.yaml
charts/thoras/tests/dashboard_deployment_test.yaml
charts/thoras/tests/monitor_deployment_test.yaml
charts/thoras/tests/monitor_v2_deployment_test.yaml
charts/thoras/tests/operator_deployment_test.yaml
charts/thoras/tests/reasoning_api_deployment_test.yaml
charts/thoras/values.yaml

Thoras users would like to have the ability to have node groups specifically for thoras workloads. 
Added `tolerations` value that is[ 1:1 with pod tolerations schema](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
```
tolerations:
- key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
```

Add node tolerations

---

charts/thoras/templates/forecast-worker/deployment.yaml
charts/thoras/tests/forecast_worker_test.yaml
charts/thoras/values.yaml

Thoras will be migrating to a queue based forecast architecture. 
Added `thorasForecast.worker.enabled`. When set to true the forecast worker pods will spin up.

added forecast-worker pods

---

charts/thoras/README.md
charts/thoras/templates/collector/pvc.yaml
charts/thoras/values.yaml

Customers should be able to set an access mode to something other than `ReadWriteOnce` if they want to decouple the service layer from the timescale/collector pod.

Add configurable persistence accessMode for the PVC

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/service.yaml
charts/thoras/tests/api_service_deployment_test.yaml
charts/thoras/tests/deployments_test.yaml
charts/thoras/values.yaml

In order to unbind the API service layer from the PVC and the collector deployment, we're adding a micro service that handles storage of blobs that will collocate inside the collector pod.

Add blob api service

---

charts/thoras/templates/collector/deployment.yaml

The collector deployment has the same name for both init containers. It fails to install due to this.
```bash
Error: 1 error occurred:
│     * Deployment.apps "metrics-collector" is invalid: spec.template.spec.initContainers[1].name: Duplicate value: "fix-dir-ownership"
```
Change the name of the second init container. The chart installs with this change.

fix: rename collector second init container

---

charts/thoras/templates/component-clusterrole.yaml

Thoras clients would like for Thoras to scale workloads that are not deployments.
Updated thoras operator service account RBAC to allow it to get/update any scale subresource (rollouts, statefulsets)

Allow thoras op to scale any resource

---

charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/monitor-v2/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/tests/all_deployments_test.yaml
charts/thoras/tests/forecast_worker_test.yaml
charts/thoras/tests/select_deployments_test.yaml
charts/thoras/values.yaml

Ensuring all containers come with sane defaults for resource specs and the ability to override them is a basic chart feature we should already have. This gives users the ability to trust k8s will provision the necessary compute for components as well the ability to customize to their own needs
* Add resource spec to deployments missing them
* Add unit tests that ensure all deployments have resource spec

Ensure resource specs on all deployments

---

charts/thoras/templates/collector/deployment.yaml

We should combine the `fix-dir-ownership` and `fix-dir-ownership-postgresql` into the same init container to both fix a helm chart issue that occurs when installing the 4.22.0 chart and also for readability.

Combine fix-dir-ownership init container

---

charts/thoras/templates/collector/cronjob.yaml
charts/thoras/tests/all_deployments_test.yaml
charts/thoras/tests/collector_cronjob_test.yaml
charts/thoras/tests/select_deployments_test.yaml

Users expect node tolerations to propagate to all workloads, even the metric cleanup job. Let's make sure it does
* Propagate node tolerations to the metric cleanup job
* Add unit test that ensures every deployment always gets tolerations
* Move nodeSelector test to the "all deployments" test

Propagate node tolerations to cleanup job

---

charts/thoras/templates/api-server-v2/deployment.yaml

We recently started using the `THORAS_NS` value in the service layer and need to make sure it stays updated.

Pass the THORAS_NS env var to the service layer

---

charts/thoras/templates/operator/deployment.yaml
charts/thoras/tests/operator_deployment_test.yaml
charts/thoras/values.yaml

Users need the ability to configure compute requests and limits for the forecast job so they can manage their nodes and resources efficiently. Let's give them that!
Allow passing in requests and limits for cpu and memory to the operator so it can configure forecast cronjobs with those values
Also add some sane defaults

Allow configuring forecast resources

---

charts/thoras/templates/operator/deployment.yaml

This env var needs to be a string, not a bool.

Make enqueue forecast setting a string

---

charts/thoras/README.md
charts/thoras/templates/forecast-worker/deployment.yaml
charts/thoras/tests/forecast_worker_test.yaml
charts/thoras/values.yaml

Now that we have a queue based methodology for forecasting, we need to prevent the queue from getting backed up by enforcing a timeout in the event of a long running forecast.
Added a new env var to the forecast worker + true-up docs for the worker

Add forecast worker timeout

---

charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/tests/collector_deployment_test.yaml
charts/thoras/values.yaml

Keep on the latest/greatest to address possible security vulnerabilities.
Updating timescale and elastic images to the latest tags.

Upgrade Elastic and Timescale versions

---

charts/thoras/templates/crd/aiscaletarget.yaml

Users may want to control the granularity of their scaling to avoid repeated small scaling events.
Added options to set scaling behavior rules in the AST

Add ability to set a scaling threshold in AST

---

charts/thoras/templates/monitor/deployment.yaml

As we add functionality to the v2 monitor, the v1 monitor needs to know whether it owns notifying about a particular alert or not.
Adding a new `V2_MONITOR_ENABLED` to the v1 monitor container.

Pass environment var to v1 monitor about v2's state

---

charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/values.yaml

16m is much to small for timescale. Increase this to a larger number and pushing request limits for other collector services higher as well.

Increase cpu requests from timescale/et al.

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/values.yaml

We need to expose the cache windows as settings for customizing during test runs.
Exposing both `SERVICE_CACHE_WINDOW` and `SERVICE_CATALOG_REFRESH_INTERVAL` as helm chart values.

Allow configuring of cache windows

---

charts/thoras/templates/api-server-v2/deployment.yaml

We need to tell prometheus where to scrape our API service metrics.
Adding annotation for the API service layer prometheus endpoint.

Export api service layer prometheus scrape endpoint

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/values.yaml

The prometheus scrape point annotations should be available regardless of other annotations.

Move prometheus-scrape-annotations

---

charts/thoras/README.md
charts/thoras/templates/agent/daemonset.yaml
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/templates/api-server-v2/service.yaml
charts/thoras/templates/collector/deployment.yaml
charts/thoras/templates/collector/service.yaml
charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/dashboard/service.yaml
charts/thoras/templates/forecast-worker/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/operator/deployment.yaml
charts/thoras/templates/operator/service.yaml
charts/thoras/templates/reasoning-api/deployment.yaml
charts/thoras/templates/reasoning-api/service.yaml
charts/thoras/values.yaml

Customers would like to specify per-service labels to drive monitoring, etc.

Add support for service-specific labeling

---

charts/thoras/README.md
charts/thoras/templates/operator/deployment.yaml
charts/thoras/values.yaml

We need to register the prometheus exporter on the operator so that the prometheus server starts to ingest metrics from it.

Expose prometheus metric exporter on operator

---

charts/thoras/tests/monitor_deployment_test.yaml
charts/thoras/values.yaml

We should default enable the v2 monitor as we begin migrating functionality from the v1 monitor

Enable v2 monitor by default

---

charts/thoras/templates/api-server-v2/service.yaml
charts/thoras/templates/collector/service.yaml
charts/thoras/templates/dashboard/service.yaml
charts/thoras/templates/operator/service.yaml
charts/thoras/templates/reasoning-api/service.yaml
charts/thoras/tests/__snapshot__/dashboard_service_test.yaml.snap

Add `name` to service ports to allow service monitor targeting.

Add name to service ports

---

charts/thoras/templates/crd/aiscaletarget.yaml

Add the `Age` column to the kubectl output
```
NAME       MODEL      HORIZONTAL   VERTICAL         AGE
frontend   balanced   auto         recommendation   37d
```

Add age to AST output

---

charts/thoras/templates/crd/aiscaletarget.yaml

Thoras user will like the ability to set how much Thoras mutates their limits to keep them inline with their requests. 
Made upper bound omitable and added optional limit prop. 
```
vertical:
containers:
- name: foo
memory:
lowerbound: 128Mi
limit:
ratio: 1.5
```

Add vertical limit config to CRD

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/values.yaml

Forecast requests made via the API (typically from a UI request) should use the forecast queue, when enabled.

Forecasts via API should use the forecast queue

---

charts/thoras/templates/operator/deployment.yaml
charts/thoras/templates/operator/service.yaml

The prometheus metrics service on the operator should be exposed so service monitors can target it.

Expose prometheus metrics port on operator

---

charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/dashboard/nginx-config-map.yaml
charts/thoras/tests/__snapshot__/dashboard_configmap_test.yaml.snap
charts/thoras/tests/all_deployments_test.yaml
charts/thoras/tests/dashboard_configmap_test.yaml
charts/thoras/tests/dashboard_deployment_test.yaml
charts/thoras/tests/select_deployments_test.yaml
charts/thoras/values.yaml

We are implementing this change to enable Thoras users to experience our newly enhanced dashboard.
The V2 Thoras dashboard will be deployed by default. Users can revert to the V1 dashboard by modifying the following configuration:
```
thorasDashboard:
v2:
enabled: false
```

Added v2 dashboard

---

charts/thoras/templates/monitor/secret.yaml

We want to make sure there's an empty string as the value of this secret no matter what. Also this is best practice
Wrap value in quotes

Ensure empty string for slack webhook URL

---

charts/thoras/templates/forecast-worker/deployment.yaml
charts/thoras/tests/forecast_worker_test.yaml

Some models will multithread automatically and bypass the cpu limit causing k8s to throttle the forecaster
set OMP_NUM_THREADS=1 by default

Set OMP_NUM_THREADS=1

---

charts/thoras/templates/component-clusterrole.yaml

The operator recently started restarting deployments/etc. when a VPA target moved from `autonomous` to `recommendation`. This is done in the reconciler but it didn't have the correct permissions.

Give operator role the ability to restart/patch deployments

---

charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/tests/api_service_deployment_test.yaml

SERVICE_POD_LOG_LABEL is used to dynamically retrieve Thoras service names.
Added environment variable SERVICE_POD_LOG_LABEL which defaults to "app.kubernetes.io/name=thoras"

Add SERVICE_POD_LOG_LABEL

---

charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/tests/collector_deployment_test.yaml
charts/thoras/values.yaml

We need to keep our third-party dependencies up-to-date.

Update third-party images

---

charts/thoras/templates/api-server-v2/rbac.yaml
charts/thoras/templates/component-clusterrole.yaml
charts/thoras/templates/dashboard/rbac.yaml
charts/thoras/tests/__snapshot__/api_service_deployment_rbac_test.yaml.snap

We support workloads other than `deployments`, including `stateful` sets. The operator and API service layer both should have privileges to `patch`, necessary for triggering workload restarts.
- opening up the RBAC roles for the operator and the API service layer to have permission to patch `*`, not just `deployments`
- removing the dashboard's ability to patch deployments since this is no longer necessary

Give operator ability to patch more than just deployments

---

charts/thoras/values.yaml

We're not confident of using timescale as the primary read for many ASTs. Reverting this to give us a chance to stress test it locally in our cluster and possibly with a customer trying this out.

Revert timescalePrimary defaulting to true

---

charts/thoras/templates/api-server-v2/deployment.yaml

We have a `/health` endpoint on the service layer and just needed to add a `readinessProbe` section to use it.

Add readiness probe to API service

---

charts/thoras/values.yaml

We initially gave timescale a request of 128Mi. However, empirical evidence suggests this should be much higher so that we can fit our indices in memory which impacts query performance. 
Increasing timescale's memory request from 128Mi to 1536Mi (1.5 Gi)

Increase timescaledb memory request

---

charts/thoras/README.md
charts/thoras/templates/dashboard/nginx-config-map.yaml
charts/thoras/tests/__snapshot__/dashboard_configmap_test.yaml.snap
charts/thoras/tests/dashboard_configmap_test.yaml
charts/thoras/values.yaml

The addition of new feature flags to the dashboard should not necessitate a complete helm release.
Added `thorasDashboard.extras` value that will be used to add feature flags to the dashboard dynamically.

Add feature flags to dashboard values

---

charts/thoras/templates/dashboard/nginx-config-map.yaml
charts/thoras/tests/__snapshot__/dashboard_configmap_test.yaml.snap

Thoras users would like to see their chart version in the dashboard.
added chart version to dashboard config to allow dashboard to display version.

Added version to dashboard config

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/tests/api_service_deployment_test.yaml
charts/thoras/values.yaml

Restarting vertical workloads based solely on CPU metrics can lead to frequent and unnecessary restarts.
A feature flag has been introduced to enable users to restart vertical workloads based on CPU forecasts. By default, this feature is disabled.

Add restart on cpu flag

---

charts/thoras/templates/dashboard/deployment.yaml
charts/thoras/templates/forecast-worker/deployment.yaml
charts/thoras/templates/monitor/deployment.yaml
charts/thoras/templates/operator/deployment.yaml

The init containers don't need to reference the fully qualified URL for the service but can instead use the intra-namespace URL.

Don't use the fully qualified service URL, just the intra-namespace URL

---

charts/thoras/README.md
charts/thoras/templates/collector/deployment.yaml
charts/thoras/values.yaml

Switching from the [timescaledb](https://hub.docker.com/r/timescale/timescaledb) images to [timescaledb-ha](https://hub.docker.com/r/timescale/timescaledb-ha) images gives us access to the Timescale Toolkit and functions that will help us aggregate and compute data for queries, such as [time_weight](https://docs.tigerdata.com/api/latest/hyperfunctions/time-weighted-calculations/time_weight/). Parameterizing this value allows us to test the `-ha` images without impacting customers until we're satisfied.
Parameterizing `metricsCollector.timescale.image`

Parameterize timescaledb's image

---

charts/thoras/templates/monitor/deployment.yaml
charts/thoras/tests/all_deployments_test.yaml
charts/thoras/tests/monitor_deployment_test.yaml
charts/thoras/values.yaml

By always enabling the v2 monitor always, we enable removing features that the v1 monitor depends on, including Elasticsearch. By enabling the removal, we enable reducing the footprint of a thoras install.
Removing the `thorasMonitorv2` flags. This flag previously governed whether the v2 monitor container would start in addition to the v1 monitor. We always want the v2 monitor to start so that there's no loss in monitor coverage.

Drop thorasMonitorV2.enabled flag

---

charts/thoras/templates/api-server-v2/pdb.yaml

Ensure maximum api availability in the event of voluntary disruptions like:
- Karpenter / Cluster autoscaler scale-downs
- Manual pod evictions
- Node drains for maintenance
On top of making the app more resilient, this should help tighten up monitoring chatter
Add PDB for our api server. Always ensure there's at least one replica available

Add PDB for api server

---

charts/thoras/README.md
charts/thoras/templates/api-server-v2/deployment.yaml
charts/thoras/values.yaml

The `timescaleSnapshotPrimary` feature flag enables testing out the updated repo in our test environments before releasing to customers.
Adding a `timescaleSnapshotPrimary` flag (default `false`) that we can use to test the new repo in our test clusters,

Add timescaleSnapshotPrimary flag

---

charts/thoras/templates/worker/deployment.yaml
charts/thoras/tests/worker_deployment_test.yaml

Allow the worker pods access to the monitor config 
added monitor config to worker pods

Add config to worker deployment

---

charts/thoras/tests/__snapshot__/collector_deployment_test.yaml.snap
charts/thoras/values.yaml

With elastic no longer necessary, we need to commit more resources to timescale to avoid OOMs.
```
POD                                 NAME               CPU(cores)   MEMORY(bytes)
metrics-collector-c88d8c796-945wr   thoras-blob-api    20m          158Mi
metrics-collector-c88d8c796-945wr   thoras-collector   0m           12Mi
metrics-collector-c88d8c796-945wr   timescaledb        692m         5012Mi
```
Increasing timescale's request to 3gb

Increase timescale default requests
